# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# ⚠️ DEAKTIVIERT: Neue Architektur (TurboModules + Fabric)
newArchEnabled=false

# ✅ AKTIVIERT: Hermes JS Engine (standard für Expo SDK 53)
hermesEnabled=true

# Expo Image Support
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Dev client inspector
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Legacy Packaging vermeiden
expo.useLegacyPackaging=false

expo.jsEngine=hermes
